version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    timezone: Europe/London
  reviewers:
    - "martincostello"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: XliffTasks
    versions:
    - "> 1.0.0-beta.19562.1"
